
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookkeeping_system?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.zhang.Pojo.Entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zhang:
        Mapper: debug
        Service: info
        Controller: info